### ISSUE TITLE
Changed nested json objects are not showing in the changeset feed.

### ISSUE THREAD

**Issue by oliverwehrens** [pivio/pivio-server#1]
If a nested object changes only the key of the object is shown in the feed not the content. Sometimes it seems to work for some attributes and sometimes not. Not clear yet why. The values are not shown. 
Reproduce: Submit a document and change the 'tag' attribute and submit again.

It shows as:

```
  {
    "document": "349534957349857387534",
    "order": 2,
    "timestamp": "2016-04-15T07:52:37.852Z",
    "fields": [
      {
        "field": "tag",
        "current": null,
        "previous": ""
      }
    ]
  },
```

**Comment by fmueller** [comment]
Relates to #3
